@Api_HostAddress = http://localhost:5226

GET {{Api_HostAddress}}/
Accept: application/json
###
GET {{Api_HostAddress}}/games
Accept: application/json
###
GET {{Api_HostAddress}}/games/2
Accept: application/json
###
